image: python:3.11

variables:
  TWINE_USERNAME: "__token__"
  # Configure these vars in Settings > CI/CD > Variables
  # TWINE_PASSWORD
  # GITLAB_TOKEN

stages:
  - test
  - build
  - publish

before_script:
  - python -m pip install --upgrade pip
  - pip install -e .
  - pip install pytest pytest-cov

test:
  stage: test
  script:
    - pytest tests/ -v --cov=wexample_wex_core
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
      when: always
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
      when: always

build:
  stage: build
  script:
    - pip install build twine
    - python -m build
  artifacts:
    paths:
      - dist/*
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
      when: always

publish_gitlab:
  stage: publish
  script:
    - pip install twine
    - TWINE_PASSWORD=${GITLAB_TOKEN} TWINE_USERNAME=gitlab-ci-token python -m twine upload --repository-url ${CI_API_V4_URL}/projects/${CI_PROJECT_ID}/packages/pypi dist/*
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
      when: always

publish_pypi:
  stage: publish
  script:
    - pip install twine
    - python -m twine upload dist/*
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
      when: always
